export const ROUTES = {
  home: '/',
  menu: '/menu',
  adminLogin: '/admin/login',
  adminDashboard: '/admin/dashboard',
  adminProductos: '/admin/productos',
  adminCategorias: '/admin/categorias',
  adminIngredientes: '/admin/ingredientes',
  adminRecetas: '/admin/recetas',
  adminPedidos: '/admin/pedidos',
  adminDelivery: '/admin/delivery',
  adminReportes: '/admin/reportes',
  adminConfiguracion: '/admin/configuracion',
  deliveryLogin: '/delivery/login',
  deliveryPanel: '/delivery',
} as const;
